### ISSUE TITLE
Merkle.sol crashes in 0.8.7

### ISSUE THREAD

**Issue by tuahear** [jdkanani/fx-portal#17]
This line
https://github.com/fx-portal/contracts/blob/d8f2fa928b2e7a81d8e84244aa91037a7aa5ca97/contracts/lib/Merkle.sol#L21

Took me 2 days to pinpoint. Migrate back to 0.7.0 works. Or.. just use i++ ?

**Comment by wschwab** [comment]
I'm going to close for now, as audits haven't detected any issue there, if there is still an issue, please reopen
