### ISSUE TITLE
Should setFxRootTunnel and setFxChildTunnel be made virtual?

### ISSUE THREAD

**Issue by superical** [jdkanani/fx-portal#21]
Currently, the `setFxRootTunnel` and `setFxChildTunnel` functions are non-virtual. Inherited classes are unable to override with their own logic or add their own modifiers to restrict anyone from calling them out of mischief.

Should these functions be made virtual intead?

**Comment by jdkanani** [comment]
That's a good point. @QEDK can you please add this?
