### ISSUE TITLE
Is the recent vulnerability fix to the mask needed for the RootTunnel too?

### ISSUE THREAD

**Issue by superical** [jdkanani/fx-portal#22]
As there was a recent vulnerability fix to revert masks that start with 0x00, does the fix also need to be done for the contracts in fx portal, especially the part where the mask will be used to produce the exit hash which supposed to be unique?

Particularly this part: https://github.com/fx-portal/contracts/blob/main/contracts/tunnel/FxBaseRootTunnel.sol#L79

The usage of the mask looks almost the same as how it is used in the contracts on the main Polygon repo. 

This was the fix applied on the contracts in the Polygon repo some time back: https://github.com/maticnetwork/contracts/pull/381/files

Which is mainly this: 
```
require(vars.branchMaskBytes[0] == 0, "incorrect mask");
```

**Comment by jdkanani** [comment]
No, it's not needed since `exitHash` removes bytes before calculating the `exitHash`.
