### ISSUE TITLE
truffle compile fails for the FxERC721ChildTunnel.sol smart contract inside examples/

### ISSUE THREAD

**Issue by adybose** [jdkanani/fx-portal#25]
When we compile the contracts using `truffle compile`, the compilation fails with the below error message:
```
TypeError: Member "ownerOf" not found or not visible after argument-dependent lookup in contract IFxERC721.
  --> project:/contracts/examples/erc721-transfer/FxERC721ChildTunnel.sol:50:31:
   |
50 |         require(msg.sender == childTokenContract.ownerOf(tokenId));
   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^

Compilation failed. See above.
```
When we investigate the above smart contract, we find that the contract `FxERC721ChildTunnel.sol` inherits from the contract `IFxERC721` which doesn't contain any definition for the function `ownerOf()`.

**Comment by QEDK** [comment]
This is addressed in #20 you should use the version released last.
