### ISSUE TITLE
recieveMessage function error 

### ISSUE THREAD

**Issue by thenswan** [jdkanani/fx-portal#27]
Hey everyone 
I started to get issues w/ this part --> https://docs.polygon.technology/docs/develop/l1-l2-communication/state-transfer
and specifically w/ recieveMessage function (Polygon-->ETH transfer). Couple days ago I tested this function and it worked and now I see a warning "Exception in contract code" and failed gas estimation in MM. Contracts did not change.

So.. I wonder if there were any updates on this state transfer in recent days or maybe some issues I am not aware of on Goerli and Mumbai nets? Thanks.

**Comment by babyplutokurt** [comment]
Hello, I am wondering how to transfer data from child to Root, how to generate the proof as an input to receiveMessage() to receive the messeges?

**Comment by thenswan** [comment]
Upgraded to the latest version of State Transfer contracts.

**Comment by thenswan** [comment]
@babyplutokurt you can find all required info w/ examples here: https://docs.polygon.technology/docs/develop/l1-l2-communication/state-transfer
