### ISSUE TITLE
Add test cases for examples

### ISSUE THREAD

**Issue by jdkanani** [jdkanani/fx-portal#3]

**Comment by coozebra** [comment]
Hi @jdkanani 
When can you deliver test cases for examples?
They are essential in practice.

**Comment by sbauch** [comment]
would be really helpful to have some test examples.

i have no clue how to unit test something like receiving a bytes message from a parent in a child contract.

I'd be happy to mock out sender validation, but my workflow right now seems to require testnet deployment and manual testing
