### ISSUE TITLE
State transfer from Polygon to Ethereum

### ISSUE THREAD

**Issue by babyplutokurt** [jdkanani/fx-portal#32]
Hello, I am wondering how to transfer data from child to Root, how to generate the proof as an input to receiveMessage() to receive the messages?
In the Doc of Polygon, it shows:
// npm i @maticnetwork/maticjs
// for goerli - mumbai testnet
const getPOSClient = (network = 'testnet', version = 'mumbai') => {
  const posClient = new POSClient()
  return posClient.init({
    log: true,
    network: network,
    version: version,
    child: {
     "matic-provider"
    },
    parent: {
     "matic-provider"
      }
    }
  });
}
posClient.exitUtil.buildPayloadForExit("burntxhash","event signature")

I am wondering how to set "matic-provider", "matic-provider" and burntxhash, event signature

**Comment by DhairyaSethi** [comment]
You can find an example implementation of initialising maticjs [here](https://github.com/maticnetwork/proof-generation-api/blob/master/src/helpers/maticClient.js)
[Documentation](https://wiki.polygon.technology/docs/develop/l1-l2-communication/fx-portal/#withdraw-tokens-on-the-root-chain) for reference.
