### ISSUE TITLE
Can we add a childToRootTokens mapping like have on the RootChainManager of the pos-portal contracts.

### ISSUE THREAD

**Issue by rahuldamodar94** [jdkanani/fx-portal#39]
Having this mapping really helps the developers as well as the tech support folks and might also be useful in some of the applications/services.

**Comment by rahuldamodar94** [comment]
Talking about this -> https://github.com/maticnetwork/pos-portal/blob/master/flat/RootChainManager.sol#L246

**Comment by QEDK** [comment]
> Having this mapping really helps the developers as well as the tech support folks and might also be useful in some of the applications/services.

Slating on implementing this in the next sprint. 👍

**Comment by QEDK** [comment]
@rahuldamodar94 before we triage this, can you mention the exact use-case we need it for, because even something like The Graph can be used for this

**Comment by rahuldamodar94** [comment]
Of course, the Graph or any data warehouse which has indexed the Mapping events can be used, but having this mapping makes it a little more easier for anyone to check directly using the contracts. The support and the solutions team often use this to address user queries ( Users at times face bridging issues and this is one of the checks that is made to ensure the token which the user is trying to bridge is actually mapped or not ). Also, I would say its better to keep things in parity with the pos bridge contracts. Was this mapping removed intentionally for some reason ?
