### ISSUE TITLE
Is this still portal functional?

### ISSUE THREAD

**Issue by jfdelgad** [jdkanani/fx-portal#9]
is this still functional?, it doesn't seem to be sync activity between ethereum and the child contract "fxChild".

Looking at the contract in mumbai, ther las activity was 3 months ago.

**Comment by jfdelgad** [comment]
It actually worked, but it took a lot to synchronize. Is there documentation on this?

**Comment by hack3r-0m** [comment]
@jfdelgad https://docs.matic.network/docs/develop/l1-l2-communication/fx-portal
